### ISSUE TITLE
OculusInteraction EngineVersion line in uplugin prevents the sample from packaging using Meta's fork of Unreal

### ISSUE THREAD

**Issue by Motanum** [oculus-samples/Unreal-InteractionSDK-Sample#1]
I had issues packaging the sample project when using Meta's for of Unreal Engine 5.4.3 because the uplugin for Meta XR Interaction SDK has a line for 'EngineVersion 5.4.0', which prevents the pluging from being packaged when using a version higher than 5.4.0, such as 5.4.3.

The solution was to open the uplugin using notepad, and remove the line for EngineVersion.

The warning went away, and the sample project packages and runs successfully.

**Comment by johngsampson** [comment]
Thank you for the feedback! We have updated our Known Issues for v69 (https://developers.meta.com/horizon/documentation/unreal/unreal-isdk-troubleshooting) and will investigate how to alleviate this for future releases.
